//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://educations.com/XmlImport", IsNullable=false)]
public partial class import {
    
    private Provider[] providerField;
    
    private decimal versionField;
    
    public import() {
        this.versionField = ((decimal)(3.0m));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("provider")]
    public Provider[] provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Provider {
    
    private ProviderTextPropertyList contentFieldsField;
    
    private ProviderCourses coursesField;
    
    private ProviderLocations locationsField;
    
    private string uniqueIdentifierField;
    
    /// <remarks/>
    public ProviderTextPropertyList contentFields {
        get {
            return this.contentFieldsField;
        }
        set {
            this.contentFieldsField = value;
        }
    }
    
    /// <remarks/>
    public ProviderCourses courses {
        get {
            return this.coursesField;
        }
        set {
            this.coursesField = value;
        }
    }
    
    /// <remarks/>
    public ProviderLocations locations {
        get {
            return this.locationsField;
        }
        set {
            this.locationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniqueIdentifier {
        get {
            return this.uniqueIdentifierField;
        }
        set {
            this.uniqueIdentifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class ProviderTextPropertyList {
    
    private ProviderTextProperty[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("field")]
    public ProviderTextProperty[] field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(providerCustom))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(providerDefault))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public abstract partial class ProviderTextProperty {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Coordinates {
    
    private double latitudeField;
    
    private double longitudeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Address {
    
    private string streetField;
    
    private string coField;
    
    private string cityField;
    
    private string zipField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string co {
        get {
            return this.coField;
        }
        set {
            this.coField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Location {
    
    private string placeField;
    
    private Address visitingAddressField;
    
    private Address mailAddressField;
    
    private Coordinates coordinatesField;
    
    private string descriptionField;
    
    private string residentialInformationField;
    
    private LocationContacts contactsField;
    
    private string nameField;
    
    private string uniqueIdentifierField;
    
    private bool hasAccomodationField;
    
    private bool hasAccomodationFieldSpecified;
    
    private bool isFoodProvidedField;
    
    private bool isFoodProvidedFieldSpecified;
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public Address visitingAddress {
        get {
            return this.visitingAddressField;
        }
        set {
            this.visitingAddressField = value;
        }
    }
    
    /// <remarks/>
    public Address mailAddress {
        get {
            return this.mailAddressField;
        }
        set {
            this.mailAddressField = value;
        }
    }
    
    /// <remarks/>
    public Coordinates coordinates {
        get {
            return this.coordinatesField;
        }
        set {
            this.coordinatesField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string residentialInformation {
        get {
            return this.residentialInformationField;
        }
        set {
            this.residentialInformationField = value;
        }
    }
    
    /// <remarks/>
    public LocationContacts contacts {
        get {
            return this.contactsField;
        }
        set {
            this.contactsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniqueIdentifier {
        get {
            return this.uniqueIdentifierField;
        }
        set {
            this.uniqueIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hasAccomodation {
        get {
            return this.hasAccomodationField;
        }
        set {
            this.hasAccomodationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hasAccomodationSpecified {
        get {
            return this.hasAccomodationFieldSpecified;
        }
        set {
            this.hasAccomodationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isFoodProvided {
        get {
            return this.isFoodProvidedField;
        }
        set {
            this.isFoodProvidedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isFoodProvidedSpecified {
        get {
            return this.isFoodProvidedFieldSpecified;
        }
        set {
            this.isFoodProvidedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class LocationContacts {
    
    private string telephoneField;
    
    private string faxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string telephone {
        get {
            return this.telephoneField;
        }
        set {
            this.telephoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Application {
    
    private string urlField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class EmailReceiverList {
    
    private EmailReceiverListReceiver[] receiverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("receiver")]
    public EmailReceiverListReceiver[] receiver {
        get {
            return this.receiverField;
        }
        set {
            this.receiverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class EmailReceiverListReceiver {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class InformationRequest {
    
    private EmailReceiverList emailReceiversField;
    
    /// <remarks/>
    public EmailReceiverList emailReceivers {
        get {
            return this.emailReceiversField;
        }
        set {
            this.emailReceiversField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class CourseDuration {
    
    private CourseDurationSpecific specificField;
    
    private string textField;
    
    /// <remarks/>
    public CourseDurationSpecific specific {
        get {
            return this.specificField;
        }
        set {
            this.specificField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class CourseDurationSpecific {
    
    private decimal valueField;
    
    private CourseDurationSpecificUnit unitField;
    
    private bool unitFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CourseDurationSpecificUnit unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitSpecified {
        get {
            return this.unitFieldSpecified;
        }
        set {
            this.unitFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public enum CourseDurationSpecificUnit {
    
    /// <remarks/>
    hours,
    
    /// <remarks/>
    days,
    
    /// <remarks/>
    weeks,
    
    /// <remarks/>
    months,
    
    /// <remarks/>
    years,
    
    /// <remarks/>
    semesters,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class CertificateList {
    
    private CertificateListCertificate[] certificateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("certificate")]
    public CertificateListCertificate[] certificate {
        get {
            return this.certificateField;
        }
        set {
            this.certificateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class CertificateListCertificate {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class CategoryList {
    
    private CategoryListCategory[] categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public CategoryListCategory[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class CategoryListCategory {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class KeywordList {
    
    private string[] keywordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("keyword")]
    public string[] keyword {
        get {
            return this.keywordField;
        }
        set {
            this.keywordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Flags {
    
    private FlagsFlag[] flagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("flag")]
    public FlagsFlag[] flag {
        get {
            return this.flagField;
        }
        set {
            this.flagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class FlagsFlag {
    
    private string nameField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class EventApplication {
    
    private string urlField;
    
    private string applicationCodeField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string applicationCode {
        get {
            return this.applicationCodeField;
        }
        set {
            this.applicationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class AdditionalInfo {
    
    private AdditionalInfoItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public AdditionalInfoItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class AdditionalInfoItem {
    
    private string keyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Text))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AlwaysOpen))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Semester))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Month))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Fixed))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public abstract partial class StartInfo {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Text : StartInfo {
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class AlwaysOpen : StartInfo {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Semester : StartInfo {
    
    private SemesterSemester semesterField;
    
    private int yearField;
    
    private bool yearFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SemesterSemester semester {
        get {
            return this.semesterField;
        }
        set {
            this.semesterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yearSpecified {
        get {
            return this.yearFieldSpecified;
        }
        set {
            this.yearFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public enum SemesterSemester {
    
    /// <remarks/>
    Spring,
    
    /// <remarks/>
    Summer,
    
    /// <remarks/>
    Fall,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Month : StartInfo {
    
    private short yearField;
    
    private bool yearFieldSpecified;
    
    private short monthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yearSpecified {
        get {
            return this.yearFieldSpecified;
        }
        set {
            this.yearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Fixed : StartInfo {
    
    private System.DateTime startDateField;
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified {
        get {
            return this.startTimeFieldSpecified;
        }
        set {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime endTime {
        get {
            return this.endTimeField;
        }
        set {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified {
        get {
            return this.endTimeFieldSpecified;
        }
        set {
            this.endTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Price {
    
    private object itemField;
    
    private decimal vatField;
    
    private bool vatFieldSpecified;
    
    private KnownCurrencies currencyField;
    
    private bool currencyFieldSpecified;
    
    private bool vatIncludedField;
    
    private bool vatIncludedFieldSpecified;
    
    private decimal priceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("discount", typeof(PriceDiscount))]
    [System.Xml.Serialization.XmlElementAttribute("discountRate", typeof(PriceDiscountRate))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vat {
        get {
            return this.vatField;
        }
        set {
            this.vatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vatSpecified {
        get {
            return this.vatFieldSpecified;
        }
        set {
            this.vatFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public KnownCurrencies currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currencySpecified {
        get {
            return this.currencyFieldSpecified;
        }
        set {
            this.currencyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool vatIncluded {
        get {
            return this.vatIncludedField;
        }
        set {
            this.vatIncludedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vatIncludedSpecified {
        get {
            return this.vatIncludedFieldSpecified;
        }
        set {
            this.vatIncludedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class PriceDiscount {
    
    private decimal valueField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class PriceDiscountRate {
    
    private decimal percentageField;
    
    private System.DateTime startDateField;
    
    private bool startDateFieldSpecified;
    
    private System.DateTime endDateField;
    
    private bool endDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startDateSpecified {
        get {
            return this.startDateFieldSpecified;
        }
        set {
            this.startDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endDateSpecified {
        get {
            return this.endDateFieldSpecified;
        }
        set {
            this.endDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public enum KnownCurrencies {
    
    /// <remarks/>
    SEK,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    NOK,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    RUB,
    
    /// <remarks/>
    SGD,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    KHR,
    
    /// <remarks/>
    PHP,
    
    /// <remarks/>
    RMB,
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    HKD,
    
    /// <remarks/>
    IDR,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DistanceEvent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AreaEvent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LocationEvent))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public abstract partial class Event {
    
    private decimal paceField;
    
    private Price priceField;
    
    private StartInfo startField;
    
    private AdditionalInfo additionalInfoField;
    
    private EventApplication applicationInfoField;
    
    private EventLastApplicationDate lastApplicationDateField;
    
    private Flags flagsField;
    
    private string uniqueIdentifierField;
    
    private string deliveryMethodField;
    
    private KnownLanguages languageField;
    
    private bool languageFieldSpecified;
    
    private string linkField;
    
    public Event() {
        this.paceField = ((decimal)(100.00m));
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "100.00")]
    public decimal pace {
        get {
            return this.paceField;
        }
        set {
            this.paceField = value;
        }
    }
    
    /// <remarks/>
    public Price price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public StartInfo start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public AdditionalInfo additionalInfo {
        get {
            return this.additionalInfoField;
        }
        set {
            this.additionalInfoField = value;
        }
    }
    
    /// <remarks/>
    public EventApplication applicationInfo {
        get {
            return this.applicationInfoField;
        }
        set {
            this.applicationInfoField = value;
        }
    }
    
    /// <remarks/>
    public EventLastApplicationDate lastApplicationDate {
        get {
            return this.lastApplicationDateField;
        }
        set {
            this.lastApplicationDateField = value;
        }
    }
    
    /// <remarks/>
    public Flags flags {
        get {
            return this.flagsField;
        }
        set {
            this.flagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniqueIdentifier {
        get {
            return this.uniqueIdentifierField;
        }
        set {
            this.uniqueIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deliveryMethod {
        get {
            return this.deliveryMethodField;
        }
        set {
            this.deliveryMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public KnownLanguages language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool languageSpecified {
        get {
            return this.languageFieldSpecified;
        }
        set {
            this.languageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class EventLastApplicationDate {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public enum KnownLanguages {
    
    /// <remarks/>
    Afrikaans,
    
    /// <remarks/>
    Arabic,
    
    /// <remarks/>
    Balinese,
    
    /// <remarks/>
    Basque,
    
    /// <remarks/>
    Buginese,
    
    /// <remarks/>
    Bulgarian,
    
    /// <remarks/>
    Chinese,
    
    /// <remarks/>
    Croatian,
    
    /// <remarks/>
    Czech,
    
    /// <remarks/>
    Danish,
    
    /// <remarks/>
    Dutch,
    
    /// <remarks/>
    English,
    
    /// <remarks/>
    Estonian,
    
    /// <remarks/>
    Filipino,
    
    /// <remarks/>
    Finnish,
    
    /// <remarks/>
    French,
    
    /// <remarks/>
    Frisian,
    
    /// <remarks/>
    German,
    
    /// <remarks/>
    Greek,
    
    /// <remarks/>
    Hebrew,
    
    /// <remarks/>
    Hindi,
    
    /// <remarks/>
    Hungarian,
    
    /// <remarks/>
    Indonesian,
    
    /// <remarks/>
    Italian,
    
    /// <remarks/>
    Japanese,
    
    /// <remarks/>
    Javanese,
    
    /// <remarks/>
    Korean,
    
    /// <remarks/>
    Latin,
    
    /// <remarks/>
    Latvian,
    
    /// <remarks/>
    Norwegian,
    
    /// <remarks/>
    Persian,
    
    /// <remarks/>
    Polish,
    
    /// <remarks/>
    Portuguese,
    
    /// <remarks/>
    Romanian,
    
    /// <remarks/>
    Russian,
    
    /// <remarks/>
    Sami,
    
    /// <remarks/>
    Sanskrit,
    
    /// <remarks/>
    Serbian,
    
    /// <remarks/>
    Slovakian,
    
    /// <remarks/>
    Slovenian,
    
    /// <remarks/>
    Somali,
    
    /// <remarks/>
    Spanish,
    
    /// <remarks/>
    Sundanese,
    
    /// <remarks/>
    Swedish,
    
    /// <remarks/>
    Tamil,
    
    /// <remarks/>
    Thai,
    
    /// <remarks/>
    Tibetan,
    
    /// <remarks/>
    Urdu,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class DistanceEvent : Event {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class AreaEvent : Event {
    
    private string placeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class LocationEvent : Event {
    
    private string locationUIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string locationUID {
        get {
            return this.locationUIDField;
        }
        set {
            this.locationUIDField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(custom))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(@default))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public abstract partial class CourseTextProperty {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class custom : CourseTextProperty {
    
    private string nameField;
    
    private bool isHtmlField;
    
    public custom() {
        this.isHtmlField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isHtml {
        get {
            return this.isHtmlField;
        }
        set {
            this.isHtmlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class @default : CourseTextProperty {
    
    private CourseDefaultTextPropertyKey nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CourseDefaultTextPropertyKey name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public enum CourseDefaultTextPropertyKey {
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    qualification,
    
    /// <remarks/>
    platform,
    
    /// <remarks/>
    degree,
    
    /// <remarks/>
    continuing,
    
    /// <remarks/>
    detailedCost,
    
    /// <remarks/>
    technicalPrerequisites,
    
    /// <remarks/>
    applicationDeadline,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class CourseTextPropertyList {
    
    private CourseTextProperty[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("field")]
    public CourseTextProperty[] field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class Course {
    
    private CourseTextPropertyList contentFieldsField;
    
    private CourseEvents eventsField;
    
    private KeywordList keywordsField;
    
    private CategoryList categoriesField;
    
    private CertificateList grantedCertificatesField;
    
    private string linkField;
    
    private CourseDuration durationField;
    
    private InformationRequest informationRequestSettingsField;
    
    private Application applicationField;
    
    private decimal creditsField;
    
    private bool creditsFieldSpecified;
    
    private string nameField;
    
    private string uniqueIdentifierField;
    
    private string courseTypeField;
    
    /// <remarks/>
    public CourseTextPropertyList contentFields {
        get {
            return this.contentFieldsField;
        }
        set {
            this.contentFieldsField = value;
        }
    }
    
    /// <remarks/>
    public CourseEvents events {
        get {
            return this.eventsField;
        }
        set {
            this.eventsField = value;
        }
    }
    
    /// <remarks/>
    public KeywordList keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    public CategoryList categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
    
    /// <remarks/>
    public CertificateList grantedCertificates {
        get {
            return this.grantedCertificatesField;
        }
        set {
            this.grantedCertificatesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    public CourseDuration duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public InformationRequest informationRequestSettings {
        get {
            return this.informationRequestSettingsField;
        }
        set {
            this.informationRequestSettingsField = value;
        }
    }
    
    /// <remarks/>
    public Application application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    public decimal credits {
        get {
            return this.creditsField;
        }
        set {
            this.creditsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creditsSpecified {
        get {
            return this.creditsFieldSpecified;
        }
        set {
            this.creditsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uniqueIdentifier {
        get {
            return this.uniqueIdentifierField;
        }
        set {
            this.uniqueIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string courseType {
        get {
            return this.courseTypeField;
        }
        set {
            this.courseTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class CourseEvents {
    
    private Event[] eventField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("event")]
    public Event[] @event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class providerCustom : ProviderTextProperty {
    
    private string nameField;
    
    private bool isHtmlField;
    
    public providerCustom() {
        this.isHtmlField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool isHtml {
        get {
            return this.isHtmlField;
        }
        set {
            this.isHtmlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public partial class providerDefault : ProviderTextProperty {
    
    private ProviderDefaultTextPropertyKey nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProviderDefaultTextPropertyKey name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://educations.com/XmlImport")]
public enum ProviderDefaultTextPropertyKey {
    
    /// <remarks/>
    description,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class ProviderCourses {
    
    private Course[] courseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("course")]
    public Course[] course {
        get {
            return this.courseField;
        }
        set {
            this.courseField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://educations.com/XmlImport")]
public partial class ProviderLocations {
    
    private Location[] locationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("location")]
    public Location[] location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}
